### ISSUE TITLE
Chap 01. code not working

### ISSUE THREAD

**Issue by mrhalite** [PacktPublishing/Mastering-iOS-11-Programming#1]
I use Xcode 9.1 but GitHub HelloContact build failed.

And during I read and follow codes step by step but some code in "func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell" makes runtime error.
The code is "let cell = tableView.dequeueReusableCell(withIdentifier: "contactCell") as! ContactTableViewCell". The error code is "Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value". The error comes from "as!".

Do you have any solution ?

**Comment by ManikandanKurup-Packt** [comment]
Please reopen the issue if it still persists.
