### ISSUE TITLE
Chapter8 Building Our App Structure in Storyboard

### ISSUE THREAD

**Issue by gainskills** [PacktPublishing/Mastering-iOS-11-Programming#3]
![image](https://user-images.githubusercontent.com/1937472/44540031-486e5e80-a738-11e8-9225-a7c20658b6e8.png)

The "Header" should be lowercase: "header".

Otherwise you will get following error:
 2018-08-24 00:44:05.032166+0800 LetsEat[25653:1061917] *** Assertion failure in -[UICollectionView _dequeueReusableViewOfKind:withIdentifier:forIndexPath:viewCategory:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit_Sim/UIKit-3698.54.4/UICollectionView.m:5283
2018-08-24 00:44:05.037242+0800 LetsEat[25653:1061917] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'could not dequeue a view of kind: UICollectionElementKindSectionHeader with identifier header - must register a nib or a class for the identifier or connect a prototype cell in a storyboard'
*** First throw call stack:
(
0  CoreFoundation 0x000000010fef41e6 __exceptionPreprocess + 294
1  libobjc.A.dylib  0x000000010e51a031 objc_exception_throw + 48
2  CoreFoundation 0x000000010fef9472 +[NSException raise:format:arguments:] + 98
3  Foundation 0x000000010dfbd652 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 193
4  UIKit  0x00000001110d7cc0 -[UICollectionView _dequeueReusableViewOfKind:withIdentifier:forIndexPath:viewCategory:] + 2475
5  UIKit  0x00000001110d80bc -[UICollectionView dequeueReusableSupplementaryViewOfKind:withReuseIdentifier:forIndexPath:] + 324
6  LetsEat  0x000000010dc09248 _T07LetsEat21ExploreViewControllerC010collectionD0So020UICollectionReusableD0CSo0gD0C_SS33viewForSupplementaryElementOfKind10Foundation9IndexPathV2attF + 296
7  LetsEat  0x000000010dc09360 _T07LetsEat21ExploreViewControllerC010collectionD0So020UICollectionReusableD0CSo0gD0C_SS33viewForSupplementaryElementOfKind10Foundation9IndexPathV2attFTo + 160
8  UIKit  0x00000001110c2405 -[UICollectionView _createPreparedSupplementaryViewForElementOfKind:atIndexPath:withLayoutAttributes:applyAttributes:] + 521
9  UIKit  0x00000001110c68cd -[UICollectionView _updateVisibleCellsNow:] + 4536
10 UIKit  0x00000001110cc688 -[UICollectionView layoutSubviews] + 364
11 UIKit  0x00000001106cd7a8 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1515
12 QuartzCore 0x00000001158c2456 -[CALayer layoutSublayers] + 177
13 QuartzCore 0x00000001158c6667 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 395
14 QuartzCore 0x000000011584d0fb _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 343
15 QuartzCore 0x000000011587a79c _ZN2CA11Transaction6commitEv + 568
16 UIKit  0x0000000110618269 __34-[UIApplication _firstCommitBlock]_block_invoke_2 + 141
17 CoreFoundation 0x000000010fe96b0c __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
18 CoreFoundation 0x000000010fe7b2db __CFRunLoopDoBlocks + 331
19 CoreFoundation 0x000000010fe7aa84 __CFRunLoopRun + 1284
20 CoreFoundation 0x000000010fe7a30b CFRunLoopRunSpecific + 635
21 GraphicsServices 0x0000000114a4ba73 GSEventRunModal + 62
22 UIKit  0x00000001105fe057 UIApplicationMain + 159
23 LetsEat  0x000000010dc07b57 main + 55
24 libdyld.dylib  0x0000000113339955 start + 1
25 ???  0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by ManikandanKurup-Packt** [comment]
Please reopen if the issue still exists

**Comment by ManikandanKurup-Packt** [comment]
Thank you for the fix!
